import { mergeNodeDefaults } from '../utils/nodeDefaults.js';
import { DEFAULT_IMAGE_GENERATION_SETTINGS } from '../utils/imageGenerationOptions.js';
import { DEFAULT_VIDEO_GENERATION_SETTINGS } from '../utils/videoGenerationOptions.js';
import { DEFAULT_EASE_CURVE_DATA } from '../lib/easingPresets.js';

export const NODE_DEFINITIONS = [
  {
    type: 'textNode',
    label: 'Text Input',
    description: '文本输入节点',
    category: 'Text',
    order: 20,
    showInConnectionMenu: true,
    inputs: [{ id: 'text:in', kind: 'text' }],
    outputs: [{ id: 'text:out', kind: 'text' }],
    defaultData: { text: '', variableName: '', autoReceiveText: false },
    defaultSize: { width: 320, height: 200 },
  },
  {
    type: 'textConstruction',
    label: 'Text Construction',
    description: '文本构建节点',
    category: 'Text',
    order: 30,
    showInConnectionMenu: true,
    inputs: [{ id: 'text:in', kind: 'text' }],
    outputs: [{ id: 'text:out', kind: 'text' }],
    defaultData: { template: '' },
  },
  {
    type: 'llmProcessor',
    label: 'LLM Processor',
    description: 'LLM 文本处理节点',
    category: 'AI',
    order: 10,
    showInConnectionMenu: true,
    inputs: [
      { id: 'text:in', kind: 'text' },
      { id: 'image:in', kind: 'image' },
    ],
    outputs: [{ id: 'text:out', kind: 'text' }],
    defaultData: {
      provider: 'Yunwu',
      model: 'gemini-3.1-flash-lite',
      temperature: 0.85,
      maxTokens: 65535,
      outputText: '',
      status: 'idle',
      enabledSkills: [],
    },
    defaultsKind: 'llmProcessor',
  },
  {
    type: 'imageNode',
    label: 'Image Generation',
    description: '图片生成节点',
    category: 'Image',
    order: 15,
    showInConnectionMenu: true,
    inputs: [
      { id: 'text:prompt', kind: 'text' },
      { id: 'image:in', kind: 'image' },
    ],
    outputs: [{ id: 'image:out', kind: 'image' }],
    defaultData: { ...DEFAULT_IMAGE_GENERATION_SETTINGS },
    defaultsKind: 'imageGeneration',
  },
  {
    type: 'audioInputNode',
    label: 'Audio Input',
    description: 'Audio material input node',
    category: 'Video',
    order: 8,
    showInConnectionMenu: true,
    inputs: [],
    outputs: [{ id: 'audio:out', kind: 'audio' }],
    defaultData: {},
    defaultSize: { width: 280, height: 160 },
  },
  {
    type: 'videoInputNode',
    label: 'Video Input',
    description: 'Video material input node',
    category: 'Video',
    order: 9,
    showInConnectionMenu: true,
    inputs: [],
    outputs: [{ id: 'video:out', kind: 'video' }],
    defaultData: {
      videoFile: null,
      videoUrl: '',
      aspectRatio: '16:9',
      naturalWidth: null,
      naturalHeight: null,
    },
    defaultSize: { width: 360, height: 203 },
  },
  {
    type: 'videoNode',
    label: 'Video Generator',
    description: 'Specs-driven video generation shell',
    category: 'Video',
    order: 10,
    showInConnectionMenu: true,
    inputs: [
      { id: 'text:prompt', kind: 'text' },
      { id: 'multiPrompt:in', kind: 'multiPrompt' },
      { id: 'omniParams:in', kind: 'omniParams' },
      { id: 'image:firstFrame', kind: 'image', label: 'First Frame' },
      { id: 'image:lastFrame', kind: 'image', label: 'Last Frame' },
      { id: 'image:references', kind: 'image', label: 'Images' },
      { id: 'video:references', kind: 'video', label: 'Videos' },
      { id: 'audio:references', kind: 'audio', label: 'Audio' },
      { id: 'image:images', kind: 'image', legacy: true },
      { id: 'image:end', kind: 'image', legacy: true },
    ],
    outputs: [
      { id: 'video:out', kind: 'video' },
      { id: 'image:lastFrame', kind: 'image', label: 'Last Frame' },
    ],
    defaultData: { ...DEFAULT_VIDEO_GENERATION_SETTINGS },
    defaultsKind: 'videoGeneration',
    defaultSize: { width: 520, height: 293 },
  },
  {
    type: 'easeCurveNode',
    label: 'Easy Curve',
    description: 'Cubic bezier speed remapping for video clips',
    category: 'Video',
    order: 18,
    showInConnectionMenu: true,
    inputs: [
      { id: 'video:in', kind: 'video', label: 'Video' },
      { id: 'easeCurve:in', kind: 'easeCurve', label: 'Curve' },
    ],
    outputs: [
      { id: 'video:out', kind: 'video', label: 'Video' },
      { id: 'easeCurve:out', kind: 'easeCurve', label: 'Curve' },
    ],
    defaultData: { ...DEFAULT_EASE_CURVE_DATA },
    defaultSize: { width: 360, height: 260 },
  },
  {
    type: 'shotListNode',
    label: 'Shot List',
    description: 'Structured multi-shot prompt list',
    category: 'Video',
    order: 20,
    showInConnectionMenu: true,
    inputs: [],
    outputs: [{ id: 'multiPrompt:out', kind: 'multiPrompt' }],
    defaultData: {
      shots: [{ id: 'shot-1', prompt: '', duration: 3 }],
    },
    defaultSize: { width: 520, height: 360 },
  },
  {
    type: 'omniComposerNode',
    label: 'Omni Composer',
    description: 'Structured Kling Omni prompt composer',
    category: 'Video',
    order: 25,
    showInConnectionMenu: true,
    inputs: [
      { id: 'image:references', kind: 'image' },
      { id: 'multiPrompt:in', kind: 'multiPrompt' },
    ],
    outputs: [{ id: 'omniParams:out', kind: 'omniParams' }],
    defaultData: {
      prompt: '',
      multiShot: false,
      shotType: 'intelligence',
      imageRoles: {},
      elements: [''],
    },
    defaultSize: { width: 520, height: 420 },
  },
  {
    type: 'splitGridNode',
    label: 'Split Grid',
    description: 'Configure an image grid split plan',
    category: 'Image',
    order: 20,
    showInConnectionMenu: true,
    inputs: [{ id: 'image:in', kind: 'image' }],
    outputs: [{ id: 'image:out', kind: 'image' }],
    defaultData: {
      layout: '2x3',
      rows: 2,
      cols: 3,
      defaultPrompt: '',
      generateSettings: { ...DEFAULT_IMAGE_GENERATION_SETTINGS },
      sourceImageUrl: '',
      previewImageUrl: '',
      slices: [],
      settingsOpen: false,
      splitReady: false,
      status: 'idle',
      error: '',
      generatedSetCount: 0,
      lastGeneratedAt: null,
    },
    defaultSize: { width: 340, height: 260 },
  },
  {
    type: 'imageCompareNode',
    label: 'Image Compare',
    description: 'Compare two images with a draggable split view',
    category: 'Image',
    order: 22,
    showInConnectionMenu: true,
    inputs: [
      { id: 'image:a', kind: 'image' },
      { id: 'image:b', kind: 'image' },
    ],
    outputs: [],
    defaultData: {
      splitPosition: 50,
    },
    defaultSize: { width: 420, height: 300 },
  },
  {
    type: 'annotateNode',
    label: 'Image Annotate',
    description: 'Annotate an image and output a composited image',
    category: 'Image',
    order: 23,
    showInConnectionMenu: true,
    inputs: [{ id: 'image:in', kind: 'image' }],
    outputs: [{ id: 'image:out', kind: 'image' }],
    defaultData: {
      annotations: [],
      annotatedImagePath: '',
      imageSize: { width: 0, height: 0 },
      sourceImageKey: '',
      brushColor: '#ff3b30',
      brushSize: 12,
      eraserMode: 'local',
      eraserSize: 24,
      updatedAt: null,
    },
    defaultSize: { width: 360, height: 260 },
  },
  {
    type: 'ar720Node',
    label: 'AR720°',
    description: 'Full spherical panorama / HDRI preview',
    category: 'Tools',
    order: 34,
    showInConnectionMenu: true,
    inputs: [{ id: 'image:in', kind: 'image' }],
    outputs: [],
    defaultData: {
      viewerState: {
        yaw: 0,
        pitch: 0,
        fov: 70,
      },
      captureSettings: {
        aspectRatio: '16:9',
        width: 1536,
        height: 864,
      },
    },
    defaultSize: { width: 380, height: 280 },
  },
  {
    type: 'panorama360Node',
    label: '360°',
    description: 'Horizontal 360 panorama preview',
    category: 'Tools',
    order: 35,
    showInConnectionMenu: true,
    inputs: [{ id: 'image:in', kind: 'image' }],
    outputs: [],
    defaultData: {
      viewerState: {
        yaw: 0,
        pitch: 0,
        fov: 70,
      },
      captureSettings: {
        aspectRatio: '16:9',
        width: 1536,
        height: 864,
      },
    },
    defaultSize: { width: 380, height: 280 },
  },
  {
    type: 'routeNode',
    label: 'Route',
    description: '文本与图片中转节点',
    category: 'Utility',
    order: 40,
    showInConnectionMenu: true,
    inputs: [
      { id: 'text:in', kind: 'text' },
      { id: 'image:in', kind: 'image' },
    ],
    outputs: [
      { id: 'text:out', kind: 'text' },
      { id: 'image:out', kind: 'image' },
    ],
    defaultData: {},
    defaultSize: { width: 280, height: 180 },
  },
  {
    type: 'outputNode',
    label: 'Output',
    description: '图片结果输出节点',
    category: 'Image',
    order: 25,
    showInConnectionMenu: true,
    inputs: [{ id: 'image:in', kind: 'image' }],
    outputs: [],
    defaultData: {
      images: [],
      selectedIndex: 0,
      displayScale: 1,
      displaySizeBase: 360,
    },
  },
  {
    type: 'imageInputNode',
    label: 'Image Input',
    description: '图片输入节点',
    category: 'Image',
    order: 50,
    showInConnectionMenu: true,
    inputs: [{ id: 'image:in', kind: 'image' }],
    outputs: [{ id: 'image:out', kind: 'image' }],
    defaultData: {},
  },
];

export const getNodeDefinition = (type) => NODE_DEFINITIONS.find((definition) => definition.type === type);

export const getNodeDefinitionText = (translate, definition, field = 'label') => {
  const key = `nodeDef.${definition?.type}.${field}`;
  const translated = translate?.(key);
  return translated && translated !== key ? translated : definition?.[field] || '';
};

const cloneDefaultData = (data = {}) => {
  if (typeof structuredClone === 'function') return structuredClone(data);
  return JSON.parse(JSON.stringify(data));
};

export const createDefaultNodeData = (type, projectPath) => ({
  projectPath,
  ...(getNodeDefinition(type)?.defaultsKind
    ? mergeNodeDefaults(getNodeDefinition(type).defaultsKind, cloneDefaultData(getNodeDefinition(type)?.defaultData || {}))
    : cloneDefaultData(getNodeDefinition(type)?.defaultData || {})),
});
